#1 Create a dicctionary that contains the number of moons each planet has
#2 Display the data with a string method (using an iteration)
#3 Display the total number of moons in the solar system
#4 Display the average number of moons by planet

#1
planet_moons = {
    'Mercury': 0,
    'Venus': 0,
    'Earth': 1,
    'Mars': 2,
    'Jupiter': 79,
    'Saturn': 82,
    'Uranus': 27,
    'Neptune': 14,
    'Pluto': 5,
    'Haumea': 2,
    'Makemake': 1,
    'Eris': 1
}

#2
for planet in planet_moons.keys():
    print(f"The planet {planet} has {planet_moons[planet]} moons.")

#3
moons = 0
for index in planet_moons.values():
    moons = moons + index
print (f"The total amount of moons in the solar system is {moons}.")

#4
avrg = moons / len(planet_moons.keys())
print(f"The average number of moons by planet is {avrg}.")
#len() returns the number of elements in the list generated by .keys()